CREATE OR REPLACE PACKAGE       SYS."PACK_HELLO_WORLD" AS
	FUNCTION "FX_HELLO_WORLD" (MYARG IN OUT NOCOPY NUMBER)
		RETURN NUMBER;
	PROCEDURE "PROC_HELLO_WORLD" (MYARG IN OUT NOCOPY NUMBER);
END;

--Edited in Aqua